require "../function"

class Crinja::Tag::For::ForLoop
  include Object

  getter iterator

  @[Crinja::Attribute]
  def length
    # TODO: replace with getter when attributes work with getter
    @length
  end

  @[Crinja::Attribute]
  def index0
    @index0
  end

  @[Crinja::Attribute]
  def revindex0
    @revindex0
  end

  @[Crinja::Attribute]
  def first
    @first
  end

  @[Crinja::Attribute]
  def last
    @last
  end

  def crinja_attribute(attr : Value) : Value
    # FIXME: Should be autogenerated by Crinja::Attribute
    # For some reason, the methods array is empty
    value = case attr.to_string
            when "length"
              self.length
            when "index0"
              self.index0
            when "revindex0"
              self.revindex0
            when "first"
              self.first
            when "last"
              self.last
            when "index"
              self.index
            when "revindex"
              self.revindex
            when "cycle"
              self.cycle
            else
              Crinja::Undefined.new(attr.to_s)
            end

    Crinja::Value.new(value)
  end

  @length : Int32 = Int32::MIN
  @revindex0 : Int32 = Int32::MIN

  def self.new(collection : Value) : self
    raw = collection.raw

    if raw.is_a?(Iterator(Value))
      new(raw)
    else
      new(collection.each, collection.size)
    end
  end

  def initialize(iterator : Iterator(Value), @length : Int32)
    initialize(iterator)

    if length < 2
      @revindex0 = 1
      @last = true
    else
      @revindex0 = length
      @last = false
    end
  end

  def initialize(@iterator : Iterator(Value))
    @index0 = -1
    @first = true
    @last = false
  end

  def each
    value = iterator.next

    while true
      if value.is_a?(Iterator::Stop)
        break
      else
        @index0 += 1
        @revindex0 -= 1 unless @length == Int32::MIN

        next_value = iterator.next
        if next_value.is_a?(Iterator::Stop)
          @last = true
          @length = index
          @revindex0 = 0
        end

        yield value.as(Value)

        value = next_value

        @first = false
      end
    end
  end

  @[Crinja::Attribute]
  def index
    index0 + 1
  end

  @[Crinja::Attribute]
  def revindex
    revindex0 == Int32::MIN ? Int32::MIN : revindex0 + 1
  end

  @[Crinja::Attribute]
  def cycle
    CycleMethod.new(self)
  end

  class CycleMethod
    include Callable

    def initialize(@loop : ForLoop)
    end

    def call(arguments : Arguments) : Value
      arguments.varargs[@loop.index0 % arguments.varargs.size]
    end
  end

  class Recursive < ForLoop
    include Callable

    setter depth0 : Int32 = 0

    def crinja_attribute(attr : Value) : Value
      # FIXME: Should be autogenerated by Crinja::Attribute
      # For some reason, the methods array is empty
      value = case attr.to_string
              when "depth"
                Crinja::Value.new(self.depth)
              when "depth0"
                Crinja::Value.new(self.depth0)
              else
                super(attr)
              end
    end

    @[Crinja::Attribute]
    def depth0
      @depth0
    end

    @loop_runner : Crinja::Tag::For::Runner

    def self.new(loop_runner, collection : Value) : self
      raw = collection.raw
      if raw.is_a?(Iterator(Value))
        new(loop_runner, raw)
      else
        new(loop_runner, collection.each, collection.size)
      end
    end

    def initialize(@loop_runner, iterator : Iterator(Value), length : Int32)
      super(iterator, length)
    end

    def initialize(@loop_runner, iterator : Iterator(Value))
      super(iterator)
    end

    def call(arguments : Arguments)
      sub_iterator = arguments.varargs.first

      sub_loop = self.class.new(@loop_runner, sub_iterator)
      sub_loop.depth0 = self.depth

      SafeString.build do |io|
        io << @loop_runner.run_loop(sub_loop).value
      end
    end

    @[Crinja::Attribute]
    def depth
      depth0 + 1
    end
  end
end
